# Generated by Django 6.1 on 2026-09-08 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0001_initial'),
        ('notifications', '0002_notificationpreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='medication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='medications.medication'),
        ),
    ]
