"""Pydantic schemas for PillSync AI Healthcare Chatbot with Multi-Source Medical Verification."""

from datetime import datetime, timezone
from typing import List, Optional, Dict, Any
from pydantic import BaseModel, Field


class AIChatMessage(BaseModel):
    """Message object for conversation context."""
    role: str = Field(..., description="Message author role: 'user', 'assistant', or 'system'")
    content: str = Field(..., description="Raw text message content")
    timestamp: Optional[str] = Field(default_factory=lambda: datetime.now(timezone.utc).isoformat())


class MedicalSourceCitation(BaseModel):
    """Authoritative medical source metadata used to verify clinical statements."""
    name: str = Field(..., description="Authoritative organization or database name, e.g. FDA, MedlinePlus")
    url: str = Field(..., description="Direct link to source document or official monograph")
    source_type: str = Field(..., description="Source classification: FDA, MedlinePlus, DailyMed, NHS, Mayo Clinic, CDC, WHO")
    relevant_excerpt: str = Field(..., description="Extracted clinical excerpt supporting the response")
    publication_date: Optional[str] = Field(None, description="Monograph or package insert date if available")
    retrieval_timestamp: str = Field(
        default_factory=lambda: datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC"),
        description="Exact timestamp when medical data was verified"
    )


class VerificationMetadata(BaseModel):
    """Complete verification summary across 2-3 authoritative medical sources."""
    verified: bool = Field(..., description="True if at least one authoritative medical source successfully verified info")
    evidence_status: str = Field(
        ...,
        description="Verification level: 'VERIFIED', 'PARTIALLY_VERIFIED', 'INSUFFICIENT_EVIDENCE', 'SOURCE_CONFLICT', 'VERIFICATION_UNAVAILABLE'"
    )
    sources_checked: int = Field(0, description="Exact number of authoritative sources retrieved and consulted")
    sources: List[MedicalSourceCitation] = Field(default_factory=list, description="List of authoritative sources cited")
    conflict_detected: bool = Field(False, description="True if conflicting indications/contraindications were detected across sources")
    conflict_summary: Optional[str] = Field(None, description="Detailed explanation of clinical divergence if detected")
    normalized_medicines: List[str] = Field(default_factory=list, description="Canonical normalized drug names identified in the prompt")
    query_type: str = Field("MEDICATION_CLINICAL", description="Classification: 'EMERGENCY', 'MEDICATION_CLINICAL', 'PILLSYNC_PLATFORM', 'OUT_OF_SCOPE'")


class AIChatRequest(BaseModel):
    """Chat request payload from patient or caregiver."""
    message: str = Field(..., min_length=1, max_length=2000, description="User question or prompt")
    conversation_history: List[AIChatMessage] = Field(default_factory=list, description="Previous conversation turns")
    include_patient_context: bool = Field(True, description="Whether to include active patient medications/schedules in context")
    patient_id: Optional[int] = Field(None, description="Optional target patient ID if requested by authorized caregiver")
    language: Optional[str] = Field("en", description="Target response language code (e.g. en, hi, te, ta, kn, ml, mr, bn, gu, pa, or)")


class AIChatResponse(BaseModel):
    """Chat response payload including AI answer and verified medical sources."""
    message: str = Field(..., description="Final markdown formatted answer generated by Gemini")
    is_medical: bool = Field(False, description="Whether question involved medical/medication clinical facts")
    is_out_of_scope: bool = Field(False, description="Whether question was unrelated to PillSync/health")
    is_emergency: bool = Field(False, description="Whether prompt triggered urgent medical emergency triage")
    verification: Optional[VerificationMetadata] = Field(None, description="Verification evidence and citations")
    suggested_prompts: List[str] = Field(default_factory=list, description="Interactive quick-reply or fallback question chips")
    disclaimer: str = Field(
        "PillSync AI Assistant provides verified educational information and does not replace professional medical advice, diagnosis, or treatment. Always consult a qualified physician or pharmacist before starting, changing, or stopping any medication.",
        description="Mandatory healthcare compliance disclaimer"
    )


class SuggestedCategory(BaseModel):
    """Categorized predefined questions."""
    category: str
    icon: str
    description: str
    questions: List[str]


class SuggestedQuestionsResponse(BaseModel):
    """List of categorized predefined questions for interactive exploration."""
    categories: List[SuggestedCategory]


class OcrVerificationRequest(BaseModel):
    """Request to verify OCR-extracted medicine name."""
    extracted_text: str = Field(..., description="Raw text identified by OCR")
    confidence: float = Field(1.0, ge=0.0, le=1.0, description="OCR confidence score between 0.0 and 1.0")


class OcrVerificationResponse(BaseModel):
    """Response verifying OCR medication name confidence and clinical details."""
    is_confident: bool
    normalized_name: Optional[str] = None
    matched_database_record: Optional[Dict[str, Any]] = None
    warning_message: Optional[str] = None
    verification: Optional[VerificationMetadata] = None
