import type { Medicine, HistoryEntry } from "@/types/medicine";
import { uid } from "./helpers";

export function makeMedicine(overrides: Partial<Medicine> = {}): Medicine {
  return {
    id: uid(),
    name: "Metformin",
    genericName: "Metformin Hydrochloride",
    brandName: "Glucophage",
    category: "Diabetes",
    type: "Tablet",
    disease: "Type 2 Diabetes",
    dosage: "500",
    unit: "mg",
    quantity: 60,
    remaining: 42,
    frequency: "Twice daily",
    reminderTime: "08:00 AM, 08:00 PM",
    foodTiming: "After food",
    doctor: "Dr. Aisha Rahman",
    hospital: "Austin Wellness Clinic",
    prescriptionNo: "RX-88213",
    description:
      "Helps control blood sugar levels in type 2 diabetes by improving insulin sensitivity.",
    usage: "Take with meals to reduce stomach upset. Do not crush or chew.",
    sideEffects: ["Nausea", "Mild stomach discomfort", "Metallic taste"],
    notes: "Avoid alcohol while on this medication.",
    status: "active",
    createdAt: "2026-05-01",
    deleted: false,
    trend: [40, 44, 48, 42, 50, 46, 52],
    ...overrides,
  };
}

export const INITIAL_MEDICINES: Medicine[] = [
  makeMedicine({ id: "m1" }),
  makeMedicine({
    id: "m2",
    name: "Atorvastatin",
    genericName: "Atorvastatin Calcium",
    brandName: "Lipitor",
    category: "Cardiac",
    disease: "High Cholesterol",
    dosage: "20",
    unit: "mg",
    quantity: 30,
    remaining: 6,
    frequency: "Once daily",
    reminderTime: "09:00 PM",
    foodTiming: "After food",
    doctor: "Dr. Aisha Rahman",
    status: "active",
    trend: [30, 28, 24, 20, 15, 10, 6],
  }),
  makeMedicine({
    id: "m3",
    name: "Amlodipine",
    genericName: "Amlodipine Besylate",
    brandName: "Norvasc",
    category: "Cardiac",
    disease: "Hypertension",
    dosage: "5",
    unit: "mg",
    quantity: 30,
    remaining: 21,
    frequency: "Once daily",
    reminderTime: "08:00 AM",
    foodTiming: "Before food",
    doctor: "Dr. Kenji Watanabe",
    status: "active",
    trend: [30, 29, 27, 25, 23, 22, 21],
  }),
  makeMedicine({
    id: "m4",
    name: "Vitamin D3",
    genericName: "Cholecalciferol",
    brandName: "D-Rise",
    category: "Supplement",
    disease: "Deficiency",
    dosage: "1000",
    unit: "IU",
    quantity: 90,
    remaining: 66,
    frequency: "Once daily",
    reminderTime: "08:00 AM",
    foodTiming: "After food",
    doctor: "Dr. Priya Nair",
    status: "active",
    trend: [90, 86, 80, 76, 72, 68, 66],
  }),
  makeMedicine({
    id: "m5",
    name: "Losartan",
    genericName: "Losartan Potassium",
    brandName: "Cozaar",
    category: "Cardiac",
    disease: "Hypertension",
    dosage: "50",
    unit: "mg",
    quantity: 30,
    remaining: 3,
    frequency: "Once daily",
    reminderTime: "08:00 PM",
    foodTiming: "After food",
    doctor: "Dr. Kenji Watanabe",
    status: "active",
    trend: [30, 24, 18, 12, 8, 5, 3],
  }),
  makeMedicine({
    id: "m6",
    name: "Omeprazole",
    genericName: "Omeprazole Magnesium",
    brandName: "Prilosec",
    category: "Gastro",
    disease: "Acid Reflux",
    dosage: "20",
    unit: "mg",
    quantity: 30,
    remaining: 0,
    frequency: "Once daily",
    reminderTime: "07:30 AM",
    foodTiming: "Before food",
    doctor: "Dr. Priya Nair",
    status: "completed",
    createdAt: "2026-06-10",
    trend: [30, 20, 12, 6, 2, 0, 0],
  }),
  makeMedicine({
    id: "m7",
    name: "Amoxicillin",
    genericName: "Amoxicillin Trihydrate",
    brandName: "Amoxil",
    category: "Antibiotic",
    disease: "Sinus Infection",
    dosage: "500",
    unit: "mg",
    quantity: 21,
    remaining: 0,
    frequency: "Thrice daily",
    reminderTime: "08:00 AM, 02:00 PM, 08:00 PM",
    foodTiming: "After food",
    doctor: "Dr. Amara Okafor",
    status: "expired",
    createdAt: "2026-04-01",
    trend: [21, 14, 8, 2, 0, 0, 0],
  }),
  makeMedicine({
    id: "m8",
    name: "Salbutamol Inhaler",
    genericName: "Albuterol Sulfate",
    brandName: "Ventolin",
    category: "Respiratory",
    type: "Inhaler",
    disease: "Asthma",
    dosage: "100",
    unit: "mcg",
    quantity: 200,
    remaining: 140,
    frequency: "As needed",
    reminderTime: "—",
    foodTiming: "Not applicable",
    doctor: "Dr. Amara Okafor",
    status: "active",
    trend: [200, 190, 175, 160, 150, 145, 140],
  }),
];

export const HISTORY_LOG: HistoryEntry[] = Array.from({ length: 40 }).map((_, i) => {
  const med = INITIAL_MEDICINES[i % INITIAL_MEDICINES.length];
  const statuses: HistoryEntry["status"][] = ["Taken", "Taken", "Taken", "Missed", "Snoozed"];
  const d = new Date(2026, 6, 30 - i);
  return {
    id: i + 1,
    date: d.toISOString().slice(0, 10),
    medicine: med.name,
    dosage: `${med.dosage}${med.unit}`,
    time: i % 2 === 0 ? "08:00 AM" : "08:00 PM",
    status: statuses[(i * 3) % statuses.length],
  };
});
